import cv2
import np

img =  cv2.imread('test.jpg')
cv2.imshow('test' , img)
cv2.waitKey(0)
#cv2.imwrite('colortest.jpg' , img)
print('Высота' , img.shape[0])
print('Ширина' , img.shape[1])
print('Количество каналов' , img.shape[2])
(b,g,r) = img[0, 0]
print(f'Красный: {r} , Зеленый: {g} , Синий: {b}')
img[0, 0] = (255, 0, 0)
(b,g,r) = img[0, 0]
print(f'Красный: {r} , Зеленый: {g} , Синий: {b}')
res_img = cv2.resize(img, (500,900), cv2.INTER_NEAREST)
cv2.imshow('измененый размер' , res_img)
cv2.waitKey(0)
h, w = img.shape[:2]
translation_matrix = np.float32([[1, 0, 200], [0, 1, 300]])
dst = cv2.warpAffine(img, translation_matrix, (w, h))
cv2.imshow('Изображение, сдвинутое вправо и вниз', dst)
cv2.waitKey(0)
crop_img = img[10:450, 300:750]
cv2.imshow('обрезка', crop_img)
cv2.waitKey(0)
center = (int(w / 2), int(h / 2))
rotation_matrix = cv2.getRotationMatrix2D(center, -45, 0.6)
rotated = cv2.warpAffine(img, rotation_matrix, (w, h))
cv2.imshow('поворот', rotated)
cv2.waitKey(0)
b, g, r = cv2.split(img)
cv2.imshow('blue', b)
cv2.waitKey(0)
cv2.imshow('green', g)
cv2.waitKey(0)
cv2.imshow('red', r)
cv2.waitKey(0)
merge_image = cv2.merge([b,g,r])
cv2.imshow('merge_image', merge_image)
cv2.waitKey(0)
image = img
img_blur_3 = cv2.blur(image, (3, 3))
cv2.imshow('img_blur_3', img_blur_3)
cv2.waitKey(0)
img_blur_7 = cv2.blur(image, (7, 7))
cv2.imshow('img_blur_7', img_blur_7)
cv2.waitKey(0)
img_blur_11 = cv2.blur(image, (11, 11))
cv2.imshow('img_blur_11', img_blur_11)
cv2.waitKey(0)
img_blur_3 = cv2.GaussianBlur(image, (3, 3), 0)
cv2.imshow('img_blur_3', img_blur_3)
cv2.waitKey(0)
img_blur_7 = cv2.GaussianBlur(image, (7, 7), 0)
cv2.imshow('img_blur_7', img_blur_7)
cv2.waitKey(0)
img_blur_11 = cv2.GaussianBlur(image, (11, 11), 0)
cv2.imshow('img_blur_11', img_blur_11)
cv2.waitKey(0)